/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AgendaManager;
import model.AgendaItem;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import javax.swing.JSpinner;
import java.util.Date;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import java.io.File;



/**
 *
 * @author MSI
 */
public class AgendaFrame extends javax.swing.JFrame {
        private AgendaManager manager;
        private int selectedIndex = -1;


    /**
     * Creates new form AgendaFrame
     */
    public AgendaFrame() {
        initComponents();
        manager = new AgendaManager();
        initSpinner();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        lblWaktu = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        lblDeskripsi = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        JScrollPane = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        lblKategori = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        lblPrioritas = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        cbPrioritas = new javax.swing.JComboBox<>();
        spnTanggal = new javax.swing.JSpinner();
        spnWaktu = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        lblCari = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda Pribadi");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("IntelOne Mono Medium", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGENDA PRIBADI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTanggal.setText("Tanggal");

        lblWaktu.setText("Waktu");

        lblJudul.setText("Judul");

        lblDeskripsi.setText("Deskripsi");

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        JScrollPane.setViewportView(txtDeskripsi);

        lblKategori.setText("Kategori");

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kuliah", "Kerja", "Pribadi", "Keluarga", " " }));

        lblStatus.setText("Status");

        lblPrioritas.setText("Prioritas");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum", "Proses", "Selesai", " " }));

        cbPrioritas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rendah", "Sedang", "Tinggi", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPrioritas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTanggal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWaktu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeskripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPrioritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJudul)
                    .addComponent(spnWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JScrollPane)
                    .addComponent(spnTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggal)
                    .addComponent(spnTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWaktu)
                    .addComponent(spnWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudul)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategori)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrioritas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbPrioritas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgenda);

        lblCari.setText("Cari            :");

        txtCari.setText(" ");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblCari, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCari)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBersih.setText("Bersih");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnTambah)
                .addGap(40, 40, 40)
                .addComponent(btnUbah)
                .addGap(29, 29, 29)
                .addComponent(btnHapus)
                .addGap(27, 27, 27)
                .addComponent(btnBersih)
                .addGap(66, 66, 66)
                .addComponent(btnImport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addGap(63, 63, 63))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnBersih)
                    .addComponent(btnImport)
                    .addComponent(btnExport))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // Format untuk mengubah Date → String
        SimpleDateFormat sdfTanggal = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat sdfWaktu   = new SimpleDateFormat("HH:mm");

        // Ambil nilai dari spinner (tipe Date) lalu format jadi String
        String tanggal   = sdfTanggal.format((Date) spnTanggal.getValue());
        String waktu     = sdfWaktu.format((Date) spnWaktu.getValue());

        // Yang lain tetap dari textfield/combobox
        String judul     = txtJudul.getText().trim();
        String deskripsi = txtDeskripsi.getText().trim();
        String kategori  = cbKategori.getSelectedItem().toString();
        String status    = cbStatus.getSelectedItem().toString();
        String prioritas = cbPrioritas.getSelectedItem().toString();

        // Validasi: minimal judul tidak boleh kosong
        if (judul.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Judul tidak boleh kosong.",
                    "Validasi",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Buat object AgendaItem
        AgendaItem item = new AgendaItem(
                tanggal,
                waktu,
                judul,
                deskripsi,
                kategori,
                status,
                prioritas
        );

        // Simpan ke manager
        manager.tambahAgenda(item);

        // Update tabel & bersihkan form
        refreshTable();
        bersihkanForm();

        JOptionPane.showMessageDialog(this,
                "Data agenda berhasil ditambahkan.",
                "Info",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgendaMouseClicked
        // baris yang diklik
        selectedIndex = tblAgenda.getSelectedRow();

        if (selectedIndex >= 0) {
            // ambil objek agenda dari manager
            AgendaItem a = manager.getSemuaAgenda().get(selectedIndex);

            // isi form dari objek AgendaItem
            txtJudul.setText(a.getJudul());
            txtDeskripsi.setText(a.getDeskripsi());
            cbKategori.setSelectedItem(a.getKategori());
            cbStatus.setSelectedItem(a.getStatus());
            cbPrioritas.setSelectedItem(a.getPrioritas());

            // atur spinner tanggal & waktu (parse dari String → Date)
            try {
                SimpleDateFormat sdfTanggal = new SimpleDateFormat("dd-MM-yyyy");
                SimpleDateFormat sdfWaktu   = new SimpleDateFormat("HH:mm");

                java.util.Date tgl = sdfTanggal.parse(a.getTanggal());
                java.util.Date wkt = sdfWaktu.parse(a.getWaktu());

                spnTanggal.setValue(tgl);
                spnWaktu.setValue(wkt);
            } catch (Exception e) {
                // kalau gagal parse, abaikan saja atau tampilkan pesan
                // JOptionPane.showMessageDialog(this, "Gagal membaca tanggal/waktu");
            }
        }
    }//GEN-LAST:event_tblAgendaMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data di tabel yang ingin diubah dulu.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // ambil nilai dari spinner tanggal & waktu
        SimpleDateFormat sdfTanggal = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat sdfWaktu   = new SimpleDateFormat("HH:mm");

        String tanggal   = sdfTanggal.format((Date) spnTanggal.getValue());
        String waktu     = sdfWaktu.format((Date) spnWaktu.getValue());
        String judul     = txtJudul.getText().trim();
        String deskripsi = txtDeskripsi.getText().trim();
        String kategori  = cbKategori.getSelectedItem().toString();
        String status    = cbStatus.getSelectedItem().toString();
        String prioritas = cbPrioritas.getSelectedItem().toString();

        if (judul.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Judul tidak boleh kosong.",
                    "Validasi",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // buat object baru
        AgendaItem itemBaru = new AgendaItem(
                tanggal,
                waktu,
                judul,
                deskripsi,
                kategori,
                status,
                prioritas
        );

        // update di manager
        manager.updateAgenda(selectedIndex, itemBaru);

        // refresh tabel & reset form
        refreshTable();
        bersihkanForm();
        selectedIndex = -1;

        JOptionPane.showMessageDialog(this,
                "Data agenda berhasil diubah.",
                "Info",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data di tabel yang ingin dihapus dulu.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus data ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            manager.hapusAgenda(selectedIndex);
            refreshTable();
            bersihkanForm();
            selectedIndex = -1;

            JOptionPane.showMessageDialog(this,
                    "Data agenda berhasil dihapus.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        bersihkanForm();               // kosongkan input
        selectedIndex = -1;            // tidak ada baris yang sedang dipilih
        tblAgenda.clearSelection();    // hilangkan highlight di tabel
    }//GEN-LAST:event_btnBersihActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String keyword = txtCari.getText().trim().toLowerCase();

       // kalau kosong, tampilkan semua saja
       if (keyword.isEmpty()) {
           refreshTable();
           return;
       }

       DefaultTableModel model = (DefaultTableModel) tblAgenda.getModel();
       model.setRowCount(0);  // kosongkan tabel dulu

       for (AgendaItem a : manager.getSemuaAgenda()) {
           if (a.getJudul().toLowerCase().contains(keyword)) {
               Object[] row = {
                   a.getTanggal(),
                   a.getWaktu(),
                   a.getJudul(),
                   a.getKategori(),
                   a.getStatus(),
                   a.getPrioritas()
               };
               model.addRow(row);
           }
       }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        if (manager.getSemuaAgenda().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Tidak ada data untuk di-export.",
                    "Export",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        exportToTxt();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        importFromTxt();
    }//GEN-LAST:event_btnImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaFrame().setVisible(true);
            }
        });
    }
private void initTable() {
    String[] kolom = {"Tanggal", "Waktu", "Judul", "Kategori", "Status", "Prioritas"};
    DefaultTableModel model = new DefaultTableModel(kolom, 0);
    tblAgenda.setModel(model);   // tblAgenda = nama JTable kamu
}

private void refreshTable() {
    DefaultTableModel model = (DefaultTableModel) tblAgenda.getModel();
    model.setRowCount(0); // hapus semua baris lama

    for (AgendaItem a : manager.getSemuaAgenda()) {
        Object[] row = {
            a.getTanggal(),
            a.getWaktu(),
            a.getJudul(),
            a.getKategori(),
            a.getStatus(),
            a.getPrioritas()
        };
        model.addRow(row);
    }
}

private void bersihkanForm() {
    // reset teks
    txtJudul.setText("");
    txtDeskripsi.setText("");

    // reset pilihan combobox
    cbKategori.setSelectedIndex(0);
    cbStatus.setSelectedIndex(0);
    cbPrioritas.setSelectedIndex(0);

    // reset spinner tanggal & waktu ke waktu sekarang
    Date now = new Date();
    spnTanggal.setValue(now);
    spnWaktu.setValue(now);

    // fokus ke judul biar enak input
    txtJudul.requestFocus();
}

private void initSpinner() {
    Date now = new Date();

    // Spinner tanggal: hanya hari, bulan, tahun
    SpinnerDateModel modelTanggal = new SpinnerDateModel(
            now,      // nilai awal
            null,     // min (boleh null)
            null,     // max (boleh null)
            Calendar.DAY_OF_MONTH  // step (naik turun per hari)
    );
    spnTanggal.setModel(modelTanggal);
    spnTanggal.setEditor(new JSpinner.DateEditor(spnTanggal, "dd-MM-yyyy"));

    // Spinner waktu: jam & menit
    SpinnerDateModel modelWaktu = new SpinnerDateModel(
            now,
            null,
            null,
            Calendar.MINUTE  // step (naik turun per menit)
    );
    spnWaktu.setModel(modelWaktu);
    spnWaktu.setEditor(new JSpinner.DateEditor(spnWaktu, "HH:mm"));
}

// Menyimpan semua data agenda ke file teks
private void exportToTxt() {
    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Pilih lokasi untuk menyimpan file agenda");

    // nama default
    chooser.setSelectedFile(new File("agenda.txt"));

    int result = chooser.showSaveDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();

        // kalau user tidak menulis .txt, tambahkan otomatis
        if (!file.getName().toLowerCase().endsWith(".txt")) {
            file = new File(file.getParentFile(), file.getName() + ".txt");
        }

        try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {

            for (AgendaItem a : manager.getSemuaAgenda()) {
                String judul     = a.getJudul().replace(";", " ");
                String deskripsi = a.getDeskripsi().replace(";", " ");

                String line = a.getTanggal()  + ";" +
                              a.getWaktu()    + ";" +
                              judul           + ";" +
                              deskripsi       + ";" +
                              a.getKategori() + ";" +
                              a.getStatus()   + ";" +
                              a.getPrioritas();

                bw.write(line);
                bw.newLine();
            }

            JOptionPane.showMessageDialog(this,
                    "Export selesai.\nFile disimpan di:\n" + file.getAbsolutePath(),
                    "Export",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi error saat export: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    // kalau CANCEL → tidak melakukan apa-apa
}


// Membaca data agenda dari file teks
private void importFromTxt() {
    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Pilih file agenda (.txt) yang akan di-import");

    int result = chooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {

            manager.clearAll();  // kosongkan data lama dulu

            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(";", -1);

                if (parts.length >= 7) {
                    String tanggal   = parts[0];
                    String waktu     = parts[1];
                    String judul     = parts[2];
                    String deskripsi = parts[3];
                    String kategori  = parts[4];
                    String status    = parts[5];
                    String prioritas = parts[6];

                    AgendaItem item = new AgendaItem(
                            tanggal, waktu, judul, deskripsi,
                            kategori, status, prioritas
                    );
                    manager.tambahAgenda(item);
                }
            }

            refreshTable();
            bersihkanForm();

            JOptionPane.showMessageDialog(this,
                    "Import selesai dari file:\n" + file.getAbsolutePath(),
                    "Import",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi error saat import: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    // kalau CANCEL → tidak melakukan apa-apa
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> cbPrioritas;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblDeskripsi;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblPrioritas;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JSpinner spnTanggal;
    private javax.swing.JSpinner spnWaktu;
    private javax.swing.JTable tblAgenda;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtJudul;
    // End of variables declaration//GEN-END:variables
}
